services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PROFILE=prd
      - DATABASE_URL=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
      - DATABASE_USER=RM550479
      - DATABASE_PWD=051202
